### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/pcp#74]
## Task

Evaluate both UX prototype and implementation source and make adjustments. This Issue's initial description may be updated with possible adjustments 

- [x] **tables**
  - [x] empty cells
  - [x] labeling tables: some could be `caption` element, most cases via `aria-labelledby="id_name"`
  - [x] `th` vs `td`
  - [x] `thead`, `tbody`, etc
- [x] **forms**
  - [x] `label`, including pairing `labelledby` when `label` labels a group that isn't specifically a form element (e.g. `radio`/`checkbox` list)
  - [x] `fieldset` and/or `legend`
  - [x] aria labeling
    - [x] 'aria-describedby`
    - [x] `aria-labelledby`
    - [x] roles, e.g. `alert`, etc
